[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
dnspython = "*"
flask = "*"
flask-socketio = "*"
guessit = "*"
imdb-cli-tool = "*"
imdbparser = "*"
imdbpy = "==6.8"
pymongo = "*"
python = "^3.7"
requests-html = "*"
